#!/bin/sh

set -e

# Remove Tahoma that was in v2.0. Only here to fix things
# up for testing / unstable users, this was never in a stable release.
rm -f  /usr/share/fonts/truetype/msttcorefonts/Tahoma.ttf
rm -f  /usr/share/fonts/truetype/msttcorefonts/tahoma.ttf
defoma-font purge truetype /usr/share/fonts/truetype/msttcorefonts/Tahoma.ttf > /dev/null || true

#DEBHELPER#

