#! /bin/sh -e

if [ -d /usr/X11R6/lib/X11/fonts/TrueType ]; then
    update-fonts-dir /usr/X11R6/lib/X11/fonts/TrueType
    if [ ! -L /usr/X11R6/lib/X11/fonts/TrueType ]; then
        rmdir --ignore-fail-on-non-empty /usr/X11R6/lib/X11/fonts/TrueType
    fi
fi

#DEBHELPER#
